# horizontal split
bind h split-window -h

# vertical split
bind v split-window -v

# reload config
bind r source-file ~/.tmux.conf

# open new window with the same directory
bind c new-window -c "#{pane_current_path}"

# M-[hjkl] for pane switching
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# M-[IJKL] for resizing a pane
bind -n M-H resize-pane -L 5
bind -n M-J resize-pane -D 5
bind -n M-K resize-pane -U 5
bind -n M-L resize-pane -R 5

# M-[uo] for window switching
bind -n M-u select-window -p
bind -n M-o select-window -n

# vim-like bindings in the copy mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

# don't rename windows automatically
set-option -g allow-rename off

set -g mouse on

# set the TERM variable to the terminal tmux is running in instead of `screen`
set -g default-terminal "$TERM"

# style
set -g status-position top
set -g status-justify left

set -g status-style 'fg=colour250 bg=colour235'

set -g status-left ''
set -g status-right '#[fg=colour235,bg=colour250] #H #[fg=colour255,bg=colour245] %H:%M #[fg=colour255,bg=colour240] %d-%m-%Y '

setw -g window-status-style 'fg=colour255 bg=colour240'
setw -g window-status-format '#I#[fg=colour100]:#[fg=colour255]#W#[fg=colour100]#F '

setw -g window-status-current-style 'fg=colour15 bg=colour17'
setw -g window-status-current-format '#I#[fg=colour1]:#[fg=colour15]#W#[fg=colour1]#F '

set -g pane-border-style 'fg=colour1 bg=colour235'
set -g pane-active-border-style 'fg=colour2 bg=colour235'
set -g pane-border-status top
set -g pane-border-format '#P:#T'
set -g pane-border-format '#P:#T'

set -g set-titles on

set -g base-index 1
set -g pane-base-index 1
